using System;
using System.Collections.Generic;
using TrackGeneration.Design;
using TrackGeneration.Planning;

namespace TrackGeneration.Tests
{
    /// <summary>
    /// V2.0 baseline preservation — the FROZEN golden corpus.
    ///
    /// Two-phase design:
    ///  • DISCOVERY (one-time, explicit): <see cref="GoldenSeedCorpusTests.DiscoverAndFreeze"/>
    ///    scans <see cref="Entry.BaseSeed"/>..+<see cref="Entry.ScanWindow"/> to find the first
    ///    seed that succeeds and satisfies <see cref="Entry.Accept"/>, then prints a paste-ready
    ///    block of frozen seeds.
    ///  • REGRESSION (normal suite): every scenario uses its EXACT frozen seed from
    ///    <see cref="FrozenSeeds"/> — no scanning. Later V2 stages therefore cannot silently
    ///    drift to a different seed inside the window; the seed is pinned in source.
    ///
    /// To freeze: run DiscoverAndFreeze once in the Unity Test Runner, paste its output into the
    /// FROZEN SEEDS block below, and commit. After that, a golden seed that fails to generate or
    /// no longer matches its baseline is a hard test FAILURE.
    /// </summary>
    public static class GoldenSeedCorpus
    {
        /// <summary>One representative scenario.</summary>
        public sealed class Entry
        {
            public string Id;
            public string Description;
            public string Preset;

            /// <summary>Discovery-only: start of the scan window. NEVER read by the regression suite.</summary>
            public int BaseSeed;

            /// <summary>Discovery-only: scan width. NEVER read by the regression suite.</summary>
            public int ScanWindow = 24;

            /// <summary>Settings mutation applied before generation (may be null).</summary>
            public Action<TrackDesignerSettings> Mutate;

            /// <summary>Acceptance predicate beyond Success (e.g. "has a loop"). Null = success is enough.</summary>
            public Func<TrackGenerationResult, bool> Accept;

            /// <summary>
            /// When true, generate with REAL editor-style settings (the pristine preset: BestValid
            /// selection + full ring density) instead of the fast test settings. Used for
            /// high-fidelity reference tracks so V2 wall/geometry work is judged against
            /// editor-scale output, not a fast approximation.
            /// </summary>
            public bool EditorFidelity;
        }

        // ─────────────────────────── FROZEN SEEDS ───────────────────────────
        // Filled ONCE by GoldenSeedCorpusTests.DiscoverAndFreeze, then committed.
        // Until an entry appears here it is "unfrozen": the regression suite reports it
        // Inconclusive (freeze pending) rather than scanning for a seed.
        //
        /// <summary>A committed golden entry: the pinned seed AND the expected V1 canonical hash.</summary>
        public readonly struct FrozenEntry
        {
            public readonly int Seed;
            public readonly string CanonicalHash;
            public FrozenEntry(int seed, string canonicalHash)
            {
                Seed = seed;
                CanonicalHash = canonicalHash;
            }
        }

        //   >>> PASTE DISCOVERY OUTPUT BETWEEN THE MARKERS BELOW <<<
        private static readonly Dictionary<string, FrozenEntry> FrozenSeeds = new Dictionary<string, FrozenEntry>
        {
            // BEGIN-FROZEN-SEEDS (auto-generated by DiscoverAndFreeze — do not hand-edit)
            { "normal_racing", new GoldenSeedCorpus.FrozenEntry(1000, "31892e5cc8f91732") },
            { "flowing", new GoldenSeedCorpus.FrozenEntry(2000, "edadb5418bd0dd29") },
            { "technical_curves", new GoldenSeedCorpus.FrozenEntry(3002, "399f5bb9bb1c9003") },
            { "velocity", new GoldenSeedCorpus.FrozenEntry(4000, "30f55590e1a699de") },
            { "switchback_banking", new GoldenSeedCorpus.FrozenEntry(5006, "c2d960487fd39a13") },
            { "rollercoaster", new GoldenSeedCorpus.FrozenEntry(6000, "238832c42ae25fe2") },
            { "wallride", new GoldenSeedCorpus.FrozenEntry(10000, "e63f4020bae3bfae") },
            { "compound", new GoldenSeedCorpus.FrozenEntry(15061, "aff750125419cc83") },
            // END-FROZEN-SEEDS
        };
        // ─────────────────────────────────────────────────────────────────────

        public static IReadOnlyList<Entry> Entries => _entries;

        /// <summary>True once the freeze has begun (at least one seed committed). Gates CI strictness.</summary>
        public static bool HasAnyFrozen => FrozenSeeds.Count > 0;

        public static bool IsFrozen(Entry e) => e != null && FrozenSeeds.ContainsKey(e.Id);

        /// <summary>The committed seed + baseline hash for a frozen entry. Throws if not frozen yet.</summary>
        public static FrozenEntry FrozenOf(Entry e)
        {
            if (e == null || !FrozenSeeds.TryGetValue(e.Id, out FrozenEntry f))
                throw new InvalidOperationException(
                    $"Corpus entry '{e?.Id}' is not frozen. Run GoldenSeedCorpusTests.DiscoverAndFreeze first.");
            return f;
        }

        /// <summary>True only when EVERY corpus entry has a committed frozen seed.</summary>
        public static bool AllFrozen()
        {
            foreach (Entry e in _entries)
                if (!FrozenSeeds.ContainsKey(e.Id)) return false;
            return true;
        }

        private static readonly List<Entry> _entries = Build();

        private static List<Entry> Build()
        {
            var list = new List<Entry>();

            void Add(string id, string desc, string preset, int baseSeed,
                Action<TrackDesignerSettings> mutate = null,
                Func<TrackGenerationResult, bool> accept = null,
                int scan = 24, bool editorFidelity = false)
                => list.Add(new Entry
                {
                    Id = id, Description = desc, Preset = preset,
                    BaseSeed = baseSeed, ScanWindow = scan, Mutate = mutate, Accept = accept,
                    EditorFidelity = editorFidelity
                });

            // ── Layout / silhouette variety (preset-driven; ordinary track, corner variety allowed) ──
            Add("normal_racing", "Balanced default racing track", TrackStylePresetLibrary.Balanced, 1000,
                mutate: DualOff, scan: 48);
            Add("flowing", "Flowing, sweeping layout", TrackStylePresetLibrary.Flowing, 2000);
            Add("technical_curves", "Technical, curve-heavy layout", TrackStylePresetLibrary.Technical, 3000);
            Add("velocity", "High-speed velocity layout", TrackStylePresetLibrary.Velocity, 4000);
            Add("switchback_banking", "Switchback, banking-heavy layout", TrackStylePresetLibrary.Switchback, 5000,
                mutate: DualOff, scan: 48);
            Add("rollercoaster", "Rollercoaster full-feature showcase", TrackStylePresetLibrary.Rollercoaster, 6000,
                mutate: DualOff, scan: 64);

            // NOTE: a dedicated "major_elevation" entry was REMOVED. Its Rollercoaster+NoStuntFeatures
            // config inherited a mandatory dual quarter (the flaky subsystem), so its pinned seed
            // did not reliably reproduce. Big-elevation coverage is already provided by
            // 'rollercoaster' (range ~958m), 'compound' (~546m) and 'normal_racing' (~668m).

            // ── Feature coverage ──
            // Dedicated single-feature "isolation" entries for loops/corkscrews/spirals/jumps/
            // pipes were REMOVED: they were redundant (the resolved entries already cover every
            // feature — loops/corks/spirals/jumps via 'rollercoaster' + 'compound', pipes via
            // 'switchback_banking', big elevation via 'major_elevation'/'rollercoaster') and, on
            // the heavy Rollercoaster canvas, they had low closure yield that made discovery
            // grind. Only the wallride entry is kept — wallrides appear on the light Balanced
            // canvas, which resolves quickly.
            Add("wallride", "Isolated: at least one wallride", TrackStylePresetLibrary.Balanced, 10000,
                mutate: s => Isolate(s, wallrides: (1, 2)),
                accept: r => r.Layout.Metrics.WallrideCount >= 1, scan: 32);

            // ── Structural / compound ──
            // NOTE: a "dual_road" corpus entry is intentionally OMITTED. Guaranteed dual-road
            // quarters have a known yield problem (road B must detour around road A yet stay
            // time-balanced). Forcing one here would just block the freeze; add it back once
            // reliable-dual generation lands.

            Add("compound", "Compound feature pattern present",
                TrackStylePresetLibrary.Rollercoaster, 15000,
                mutate: s =>
                {
                    DualOff(s);
                    s.Features.CompoundFeatureChance = 1f;
                    s.Features.Loops = new TrackFeatureRule(true, 1, 1, 1f);
                    s.Features.Corkscrews = new TrackFeatureRule(true, 1, 1, 1f);
                },
                accept: r => r.Layout.Metrics.CompoundPatternCount >= 1, scan: 64);

            // NOTE: editor-fidelity references (full-res BestValid) are intentionally NOT part of
            // discovery scanning — that is far too slow. Once the fast corpus is frozen and we know
            // a good full-res seed (e.g. your 1053509338 WITH its actual scene settings), we add it
            // as a SINGLE exact-pinned editor-fidelity entry (one generation, not a scan).

            return list;
        }

        // ── Mutation helpers ──

        /// <summary>
        /// Disable every vertical/rotational STUNT feature (loops, corkscrews, spirals,
        /// half-loops, full pipes, wallrides, jumps). Ordinary curves AND corner-variety
        /// patterns (hairpins/chicanes/S-curves) remain — those are ordinary track content.
        /// </summary>
        private static void NoStuntFeatures(TrackDesignerSettings s)
        {
            s.Features.Loops = new TrackFeatureRule(true, 0, 0, 0f);
            s.Features.Corkscrews = new TrackFeatureRule(true, 0, 0, 0f);
            s.Features.Spirals = new TrackFeatureRule(true, 0, 0, 0f);
            s.Features.HalfLoops = new TrackFeatureRule(true, 0, 0, 0f);
            s.Features.FullPipes = new TrackFeatureRule(true, 0, 0, 0f);
            s.Features.Wallrides = new TrackFeatureRule(true, 0, 0, 0f);
            s.Features.Jumps = new TrackFeatureRule(true, 0, 0, 0f);
            s.Features.MinFeatureGroups = 0;
        }

        /// <summary>
        /// Relax a mandatory dual-road quarter to optional. Balanced/Rollercoaster/Switchback
        /// force MinimumDualQuarterCount = 1, but dual quarters are rare even in editor runs, so
        /// that requirement is the dominant discovery yield-killer. Dual coverage has its own
        /// dedicated (editor-fidelity) entry.
        /// </summary>
        private static void DualOff(TrackDesignerSettings s)
        {
            s.Quarters.MinimumDualQuarterCount = 0;
        }

        /// <summary>
        /// Suppress corner-variety patterns (hairpins, chicanes, S-curves). Used for ISOLATED
        /// single-feature baselines so the only special content is the feature under test.
        /// (Hairpin/Chicane/S-Curve are ordinary corner realizations, not stunts, so they are
        /// only suppressed here — not in the ordinary-road / elevation scenarios.)
        /// </summary>
        private static void NoCornerVariety(TrackDesignerSettings s)
        {
            s.Features.Hairpins = new TrackFeatureRule(true, 0, 0, 0f);
            s.Features.Chicanes = new TrackFeatureRule(true, 0, 0, 0f);
            s.Features.SCurves = new TrackFeatureRule(true, 0, 0, 0f);
        }

        /// <summary>
        /// Genuine single-feature isolation: everything off except the requested family, plus
        /// no dual quarters. Requires exactly the one family so the baseline is unambiguous.
        /// </summary>
        private static void Isolate(TrackDesignerSettings s,
            (int min, int max)? loops = null, (int min, int max)? corks = null,
            (int min, int max)? spirals = null, (int min, int max)? wallrides = null,
            (int min, int max)? jumps = null, (int min, int max)? pipes = null)
        {
            NoStuntFeatures(s);
            NoCornerVariety(s);

            if (loops.HasValue) s.Features.Loops = new TrackFeatureRule(true, loops.Value.min, loops.Value.max, 1.5f);
            if (corks.HasValue) s.Features.Corkscrews = new TrackFeatureRule(true, corks.Value.min, corks.Value.max, 1.5f);
            if (spirals.HasValue) s.Features.Spirals = new TrackFeatureRule(true, spirals.Value.min, spirals.Value.max, 1f);
            if (wallrides.HasValue) s.Features.Wallrides = new TrackFeatureRule(true, wallrides.Value.min, wallrides.Value.max, 1f);
            if (jumps.HasValue) s.Features.Jumps = new TrackFeatureRule(true, jumps.Value.min, jumps.Value.max, 1f);
            if (pipes.HasValue) s.Features.FullPipes = new TrackFeatureRule(true, pipes.Value.min, pipes.Value.max, 1f);

            s.Features.MinFeatureGroups = 1;
            s.Quarters.MinimumDualQuarterCount = 0;
            s.Quarters.MaximumDualQuarterCount = 0;
        }
    }
}
